import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert';
import { runLoop } from '../src/loop.js';
import { loadState } from '../src/state.js';

const projDir = process.cwd();
const forgeDir = path.join(projDir, '.forge');

function cleanUp() {
  if (fs.existsSync(forgeDir)) {
    fs.rmSync(forgeDir, { recursive: true, force: true });
  }
}

async function run() {
  console.log('--- Starting Milestone 4 Verification ---');
  cleanUp();

  console.log('Starting Forge loop in MOCK mode...');
  // Run the loop end-to-end
  await runLoop({
    objective: 'build a group bill splitting app',
    isNew: true,
    projDir,
    mock: true,
    demo: false
  });

  console.log('\nEvaluating completed run state on disk...');
  const state = loadState(projDir);
  assert.ok(state, 'State file should exist on disk.');

  // 1. Assert plan completion
  console.log('Asserting task graph outcomes...');
  assert.strictEqual(state.plan.length, 3, 'Plan should contain exactly 3 tasks generated by mock planner.');
  assert.ok(state.plan.every(t => t.status === 'done'), 'All tasks should be marked "done".');
  console.log('🟢 All 3 tasks completed successfully.');

  // 2. Assert error signatures and hypotheses count
  console.log('Asserting hypotheses registry...');
  // We expected exactly 2 failures on Task 2, meaning 2 hypotheses should be saved.
  assert.strictEqual(state.hypotheses.length, 2, 'Should have registered exactly 2 failure recovery attempts.');
  
  const h1 = state.hypotheses[0];
  const h2 = state.hypotheses[1];
  assert.strictEqual(h1.error_signature, 'ReferenceError: activeTab is not defined', 'Should capture correct error signature.');
  assert.strictEqual(h2.error_signature, 'ReferenceError: activeTab is not defined', 'Should recognize same signature across attempts.');
  assert.strictEqual(h1.outcome, 'failed', 'First hypothesis should be resolved to failed.');
  assert.strictEqual(h2.outcome, 'success', 'Second hypothesis should be resolved to success.');
  console.log('🟢 Hypotheses successfully registered and resolved.');

  // 3. Assert file ledger and build history
  console.log('Asserting ledger & history...');
  assert.ok(state.file_ledger['dist/manifest.json'], 'Ledger should record dist/manifest.json.');
  assert.ok(state.file_ledger['dist/app.js'], 'Ledger should record dist/app.js.');
  assert.ok(state.build_history.length >= 4, 'Build history should contain multiple check attempts.');
  console.log('🟢 File ledger and build history are in perfect order.');

  // Clean up
  cleanUp();
  console.log('\n--- Verification Finished: ALL PASS ---');
}

run().catch(err => {
  console.error('Loop integration test failed:', err);
  process.exit(1);
});
